from _groupsig import lib, ffi

IERROR = lib.IERROR
IOK = lib.IOK
GL19_CODE = lib.GROUPSIG_GL19_CODE
GL19_JOIN_START = lib.GL19_JOIN_START
GL19_JOIN_SEQ = lib.GL19_JOIN_SEQ
BBS04_CODE = lib.GROUPSIG_BBS04_CODE
BBS04_JOIN_START = lib.BBS04_JOIN_START
BBS04_JOIN_SEQ = lib.BBS04_JOIN_SEQ


