name: CICD
on: [push, pull_request]
jobs:
  # Regular C build with two compilers, using cmakeflags:
  build_using_compiler_in_cmakeflags:
    strategy:
        matrix:
          compiler:
            - gcc
            - clang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      - uses: docker://lpenz/ghaction-cmake:v0.9
        with:
          dependencies_debian: libssl-dev
          cmakeflags: ${{ format('-DCMAKE_C_COMPILER={0}', matrix.compiler) }}
