name: Application Framework Build with Unit Tests

on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Linux dependencies
        if: "contains( matrix.os, 'ubuntu')"
        run: sudo apt-get install libssl-dev googletest libgtest-dev
      - name: Build with Unit Tests
        uses: lukka/run-cmake@v1
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeGenerator: UnixMakefiles
#          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAppendedArgs:  '-DUSE_GTEST=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON'
          buildDirectory: ${{ github.workspace }}/build
#          useVcpkgToolchainFile: false
      - name: Run Unit Tests #Linux
#        if: "contains( matrix.os, 'ubuntu')"
        shell: bash
        run: |
          ctest --output-on-failure .
          ctest --output-on-failure -T memcheck .
