name: Application Framework Build with Unit Tests

on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Linux dependencies via apt
        if: "contains( matrix.os, 'ubuntu')"
        run: | 
	  sudo apt-get install libssl-dev googletest libgtest-dev
          # https://askubuntu.com/questions/145887/why-no-library-files-installed-for-google-test
          echo "/usr/lib" && ls /usr/lib
          echo "/../x86_64-linux-gnu/" && ls /usr/lib/x86_64-linux-gnu/
      - name: Build with Unit Tests
        uses: lukka/run-cmake@v1
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeGenerator: UnixMakefiles
          cmakeAppendedArgs: '-DUSE_GTEST=ON'
          buildDirectory: ${{ github.workspace }}/build
#          useVcpkgToolchainFile: false
      - name: Run Unit Tests #Linux
#        if: "contains( matrix.os, 'ubuntu')"
        shell: bash
        run: |
          ctest --output-on-failure .
#          ctest --output-on-failure -T memcheck .
